### ISSUE TITLE
Test k8s Jobs

### ISSUE THREAD

**Issue by miekg** [virtual-kubelet/systemk#41]
I need something to run once (across all nodes - which Jobs doesn't do), but Jobs make heavy use of restartPolicy, so we should check how they fare with systemk

**Comment by pires** [comment]
Job is an envelope for a Pod, much like a ReplicaSet (DaemonSet,Deployment,StatefulSet) and a CronJob, so there's nothing to be done in systemk to run a Pod brought up by the Job controller. `restartPolicy` is something that can be set for any Pod so if that's what you want to test/implement, I suggest clarifying the title and description of the issue.

**Comment by miekg** [comment]
Haven't got the spare cycles to do this now, and it will probably just work. Also don't really need Jobs atm. Closing. Will revisit at some future time.
