### ISSUE TITLE
Stop chowning paths from systemk

### ISSUE THREAD

**Issue by miekg** [virtual-kubelet/systemk#53]
I *think* (not sure here) that we want to outsource the creation/chowning of files and directories to systemd. I thought of this before but the thinking back then was this will be too much shell scripting. 

I'm coming back to this because permissions: if we (systemk binary) doesn't do it, we can run root-less pretty easily and just outsource it to systemd.

<strike>Alternatively we can write a little go utility that does this and *that* gets called from systemd, main point(s) being systemk doesn't do this, something called from a unit file does does. This also removed state tracking from systemk, as we just create more units. Ordering will be done with `Before:` and `After:`.</strike>
This can just be done with (multiple) ExecPreStart and ExecPostStops (see comments below)

Keeping systemk stateless is _also_ worth while.

**Comment by miekg** [comment]
See https://github.com/virtual-kubelet/systemk/pull/56 for an attempt in cmd/systemk-volume
When completed this moves most of volumes.go out of systemk itself.

@pires: what do you think: should we pursue this? If we implement health checks we still would have state in systemk. Maybe even the health checking can be outsourced to systemd - have not given that any thought.

**Comment by pires** [comment]
More units or more `ExecStartPre` and `ExecPostStop` per unit?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [virtual-kubelet/systemk] Stop ..." ]
>More units or more ExecStartPre and ExecPostStop per unit?

ExecPreStarts and ExecPostStops are better yes. So *no* more units.

/Miek

--
Miek Gieben

**Comment by pires** [comment]
Chowning and cleaning paths seem fine. But I'm not sure if that's enough to get us to run systemk as non-root. Don't we need permissions to use the dbus API to create/query units?

Following up, Liveness and Readiness probes happen following each Pod spec, and the result has impact on Pod status reporting, including the Pod's conditions, so my immediate thinking is that it should happen at the systemk level, not systemd. I also think we should be careful about delegating all to systemd because that translates to files on disk that we can leave behind on non-graceful terminations of systemk or after errors in clean-up, as systemk won't retry.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [virtual-kubelet/systemk] Stop ..." ]
>Don't we need permissions to use the dbus API to
>create/query units?

don't actually know that - worth finding out. I'm assuming being a systemd group would
suffice, but priv esc. is a thing so maybe this whole point is moot?

>Following up, Liveness and Readiness probes happen following each Pod spec, and
>the result has impact on Pod status reporting, including the Pod's conditions,
>so my immediate thinking is that it should happen at the systemk level, not
>systemd. I also think we should be careful about delegating all to systemd
>because that translates to files on disk that we can leave behind on
>non-graceful terminations of systemk or after errors in clean-up, as systemk
>won't retry.

Fair, but we already have files on disk anyway? I get your point about HC, but on a crash
you would loose the HC of running pods, resulting in them getting killed, while having
them in systemd (in whatever form - if even possible), we make them resume and everything
will keep on working (so you'd hope)

/Miek

--
Miek Gieben

**Comment by pires** [comment]
Since there's no probe support in systemk I'm fine doing it in systemd and reassessing in the future if we learn it wasn't the best option.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [virtual-kubelet/systemk] Stop ..." ]
>Since there's no probe support in systemk I'm fine doing it in systemd and
>reassessing in the future if we learn it wasn't the best option.

:-) OTOH is *much* easier doing it in systemk then outsourcing it to systemk and
retreiving the state somehow?

I think we can kick this particular can a bit, for when we actually need these probes.

**Comment by pires** [comment]
Agreed.
