### ISSUE TITLE
[question] systemk <-> k3s server tunnel ?

### ISSUE THREAD

**Issue by sureshsankaran** [virtual-kubelet/systemk#54]
does systemk vk use k3s remotedialer to setup tunnel with k3s server ? I dont see it referenced in this repo. If not, does it mean vk (or any worker node) can join k3s cluster without tunnel ?

**Comment by miekg** [comment]
if have no idea why k3s needs that tunnel or why it's even useful. Systemk doesn't use it and seems to work fine.
