### ISSUE TITLE
Flag --nodename doesn't work

### ISSUE THREAD

**Issue by pires** [virtual-kubelet/systemk#6]
In VK, it is possible to define the hostname that a virtual node will be registered with in Kubernetes. However, this is not possible here given a bunch of calls to https://github.com/virtual-kubelet/systemk/blob/745f9582221adbfc34659b444dd11214d4da0f95/pkg/system/system.go#L42-L52. These calls happen in the included `NodeProvider` implementation https://github.com/virtual-kubelet/systemk/blob/745f9582221adbfc34659b444dd11214d4da0f95/systemd/node.go#L24-L33

I think the flag should either be _removed_ (inherited from `virtual-kubelet/node-cli`) or somehow be respected in the first block.

**Comment by miekg** [comment]
fair, but when it this useful? Why do you need to override the (host)name?

**Comment by pires** [comment]
Well, good question: the code listed above does allow to do so by setting `HOSTNAME` env var. What was the reasoning behind that? Anyways, I think said mode and related flag are respected or dropped entirely.

Now, there are a few scenarios where passing the hostname may make sense:
- the provider is running side-by-side w/ a kubelet  - as is the case for k3s if I got its architecture right - and there can't be two Node resources w/ same name;
- the provider is running as a privileged Pod and the hostname may be meaningless to the user.
- the user wants it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [virtual-kubelet/systemk] Flag ..." ]
>Well, good question: the code listed above does allow to do so by setting
>HOSTNAME env var. What was the reasoning behind that? Anyways, I think said
>mode and related flag are respected or dropped entirely.
>
>Now, there are a few scenarios where passing the hostname may make sense:
>
>  • the provider is running side-by-side w/ a kubelet - as is the case for k3s
>    if I got its architecture right - and there can't be two Node resources w/
>    same name;
>  • the provider is running as a privileged Pod and the hostname may be
>    meaningless to the user.
>  • the user wants it.

Adding an ack on dropping this entirely - if someday the need arises we can resurrect.

**Comment by pires** [comment]
OK. Can I pick it up?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [virtual-kubelet/systemk] Flag ..." ]
>OK. Can I pick it up?

sure!

It's pretty hidden from us. I tried some simple things, but failed.
